import type { Metadata } from 'next'
import '@/styles/globals.css'
import Footer from '@/components/ui/Footer'
import Nav from '@/components/Nav'

export const metadata: Metadata = {
  title: {
    default: 'tripmate',
    template: '%s|trpmate',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
